#!/usr/bin/python

from hashlib import md5
from string import upper
from sys import argv
def md5_3(a):
    a=md5(a).digest()
    a=md5(a).digest()
    return upper(md5(a).hexdigest())

print md5_3(argv[1])
